### ISSUE TITLE
Linux - flasher fails to open port even though user belongs to dialup group.

### ISSUE THREAD

**Issue by amolds-zz** [thingsSDK/flasher.js#47]
> flasher.js@1.0.0 start /home/test/flasher.js
> electron .

{"name":"flasher.js","hostname":"yamhill","pid":1887,"level":30,"msg":"Opening port... SerialPort {\n  domain: null,\n  _events: \n   { error: [ [Function: onerror], [Function], [Function: onerror] ],\n     data: [Function: ondata],\n     end: [ [Function: onend], [Function: cleanup] ],\n     close: [ [Function: onclose], [Function: cleanup], [Object] ],\n     unpipe: [Function: onunpipe],\n     drain: [Function],\n     finish: { [Function: g] listener: [Function: onfinish] } },\n  _eventsCount: 7,\n  _maxListeners: undefined,\n  path: '/dev/ttyUSB0',\n  fd: null,\n  paused: true,\n  opening: true,\n  closing: false,\n  bufferSize: 65536,\n  readable: true,\n  reading: false,\n  options: \n   { baudRate: 115200,\n     autoOpen: false,\n     parity: 'none',\n     xon: false,\n     xoff: false,\n     xany: false,\n     rtscts: false,\n     hupcl: true,\n     dataBits: 8,\n     stopBits: 1,\n     bufferSize: 65536,\n     lock: true,\n     parser: [Function: raw],\n     platformOptions: { vmin: 1, vtime: 0 },\n     dsrdtr: false,\n     disconnectedCallback: [Function: bound ],\n     dataCallback: [Function: bound raw] } }","time":"2016-10-17T19:40:30.002Z","v":0}
{"name":"flasher.js","hostname":"yamhill","pid":1887,"level":30,"msg":"Preparing flash address 0 undefined","time":"2016-10-17T19:40:30.005Z","v":0}
{"name":"flasher.js","hostname":"yamhill","pid":1887,"level":30,"msg":"SlipEncoder._transform buffer","time":"2016-10-17T19:40:30.006Z","v":0}
{"name":"flasher.js","hostname":"yamhill","pid":1887,"level":50,"msg":"PORT ERROR Error: Port is not open\n    at SerialPort.write (/home/test/flasher.js/node_modules/serialport/lib/serialport.js:218:24)\n    at SlipEncoder.ondata (_stream_readable.js:555:20)\n    at emitOne (events.js:96:13)\n    at SlipEncoder.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:172:18)\n    at SlipEncoder.Readable.push (_stream_readable.js:130:10)\n    at SlipEncoder.Transform.push (_stream_transform.js:128:32)\n    at SlipEncoder._transform (/home/test/flasher.js/back-end/streams/slip.js:84:14)\n    at SlipEncoder.Transform._read (_stream_transform.js:167:10)\n    at SlipEncoder.Transform._write (_stream_transform.js:155:12)","time":"2016-10-17T19:40:30.008Z","v":0}
{"name":"flasher.js","hostname":"yamhill","pid":1887,"level":30,"msg":"Listening once FLASH_DOWNLOAD_BEGIN","time":"2016-10-17T19:40:30.009Z","v":0}
{"name":"flasher.js","hostname":"yamhill","pid":1887,"level":50,"msg":"Oh noes! true","time":"2016-10-17T19:40:30.009Z","v":0}
{"name":"flasher.js","hostname":"yamhill","pid":1887,"level":30,"msg":"Delaying for 10 ms","time":"2016-10-17T19:40:30.010Z","v":0}
test@yamhill:~/flasher.js$

**Comment by amolds-zz** [comment]
[strace.txt](https://github.com/thingsSDK/flasher.js/files/534524/strace.txt)

**Comment by chalkers** [comment]
Does this still happen with 1.1.0?

**Comment by chalkers** [comment]
Hey @amolds what version of Linux are you running - someone created a pull request #50 suggesting that there may be other usergroups tty and uucp...can you see if they are possible usergroups on your distro.

**Comment by amolds-zz** [comment]
ubuntu 16


Aaron Olds amolds@hotmail.com


________________________________
