### ISSUE TITLE
which node version

### ISSUE THREAD

**Issue by michapixel** [thingsSDK/flasher.js#51]
i'm on windows 10. first i tried the latest node version (7.x.x) installation of thingssdk succeeded but i wasn't able to "npm run dev". 
so i switched back (using https://github.com/marcelklehr/nodist) to 4.7.2 to try an older version (just picked a really old one here. 
but now i get such error:

```
 thingssdk new helloworld
```
results in:
```
c:\Program Files (x86)\Nodist\bin\node_modules\thingssdk-cli\lib\commands\devices.js:3
const {createDevicesJSON} = require('../devices');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at Object.require (internal/module.js:12:17)
    at c:\Program Files (x86)\Nodist\bin\node_modules\thingssdk-cli\node_modules\yargs\node_modules\require-directory\index.js:76:17
    at Array.forEach (native)
    at requireDirectory (c:\Program Files (x86)\Nodist\bin\node_modules\thingssdk-cli\node_modules\yargs\node_modules\require-directory\index.js:59:24)
```

So my question is: which node versions should i use under windows?

**Comment by chalkers** [comment]
Hi there,

We officially support Node 6 and will jump to 8 when LTS switches to that.

**Comment by chalkers** [comment]
Also, this issue is filed under flasher.js not thingssdk-cli :)

**Comment by michapixel** [comment]
Ah, sorry, i hadn't found the repo yet, but have now. i have it working now.
